### ISSUE TITLE
question while loading pretrained models

### ISSUE THREAD

**Issue by koalaaaaaaaaa** [MinkaiXu/GeoLDM#7]
Thanks for your code @MinkaiXu  a lot : ), it's cool.
I met a problem in loading pretrained models, the error message is as follows:
`Traceback (most recent call last):
  File "eval_analyze.py", line 198, in <module>
    main()
  File "eval_analyze.py", line 127, in main
    with open(join(eval_args.model_path, 'args.pickle'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/qm9_p/args.pickle'`
I'm confused how to solve it. Hope you'll help me with it!

**Comment by koalaaaaaaaaa** [comment]
simply unzip the downloaded file will work.
